const ActionTypes = {
    SET_GISTS_TO_STORE: 'SET_GISTS_TO_STORE',
    GET_GISTS_FROM_STORE: 'GET_GISTS_FROM_STORE',
    FETCH_GISTS: 'FETCH_GISTS',
    SET_LOADER: 'SET_LOADER',
    SELECT_GIST: 'SELECT_GIST',
    SET_PAGE: 'SET_PAGE',
    SET_PAGINATION_DATA: 'SET_PAGINATION_DATA',
    SET_STATUS_CODE: 'SET_STATUS_CODE'
};

export default ActionTypes;
